name: CI/CD Pipeline to Kubernetes

on:
    push:
       branches: [ "main" ]
    pull_request:
       branches: [ "main" ]

jobs:
 unit-test:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11.3
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.3'

    - name: Install dependencies and run migrations
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate

    - name: Run unit tests
      run: |
        python manage.py test

 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-django-app .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/my-django-app:latest   
    # - name: Push Docker image to DockerHub
    #   run: |
    #     docker tag my-django-app ${{ secrets.DOCKERHUB_USERNAME }}/my-django-app:latest
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-django-app:latest

 code-analysis:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - uses: actions/cache@v3
        with:
          key: pip-cache
          path: ~/.cache/pip
      - run: pip install --upgrade pip
      - run: pip install pylint flake8 coverage pytest-cov
      - run: pylint ./my_app/**/*.py
      - run: flake8 ./my_app/**/*.py
      - run: coverage run -m pytest tests/
      - run: coverage report -m
      - uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint.html
      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov/index.html

 deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: start minikube
          id: minikube
          uses: medyagh/setup-minikube@latest
        # now you can run kubectl to see the pods in the cluster
        - name: kubectl commands
          run: |
            minikube addons enable heapster 
            kubectl apply -f ./kubernetes/
            kubectl get all -n devsu
