name: CI/CD Pipeline

on:
    push:
       branches: [ "main" ]
    pull_request:
       branches: [ "main" ]

jobs:
 unit-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.3]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run migrations
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate

    - name: Run unit tests
      run: |
        python manage.py test

 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-django-app .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/my-django-app:latest   
    # - name: Push Docker image to DockerHub
    #   run: |
    #     docker tag my-django-app ${{ secrets.DOCKERHUB_USERNAME }}/my-django-app:latest
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-django-app:latest

 deploy:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
        matrix:
          python-version: [3.11.3]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate

    - name: Pull latest Docker image from DockerHub
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-django-app:latest

    - name: Deploy to Docker container
      run: |
        docker run -d -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/my-django-app:latest